// GENERATED by design-system/build.mjs from tokens.json. DO NOT EDIT. Change tokens.json and re-run.

/** Semantic colours, light. Only for code that can't use the CSS variables. */
export const colors = {
  background: "#FFFFFF", // Page/screen canvas
  foreground: "#000000", // Primary text, icons, the mark
  surface: "#F6F6F6", // Cards, info panels, icon buttons, inputs
  surfaceHover: "#EFEFEF", // Pressed/hover state of surface
  primary: "#000000", // Primary CTA fill
  primaryForeground: "#FFFFFF", // Text on primary CTA
  mutedForeground: "#666666", // Labels, metadata, timestamps
  subtleForeground: "#8F8F8F", // Only for text >= 18px or decorative
  border: "#E6E6E6", // Hairlines, dividers
  highlight: "#91CDFF", // Count/streak badges ONLY
  highlightForeground: "#000000", // Text on highlight
  destructive: "#C0281C", // Errors, destructive actions (proposed)
  destructiveForeground: "#FFFFFF", // Text on destructive
  ring: "#000000", // Focus ring
} as const;
