import type { Metadata } from 'next';
import Link from 'next/link';

import { ContentPage } from '@/components/content/ContentPage';
import { Callout, PreserveCase, Prose } from '@/components/content/Prose';
import {
  CONTENT_AUTHENTICITY_URL,
  ROUTES,
  SECTION_LINKS,
  VERIFICATION_SECTIONS,
} from '@/content/site';

export const metadata: Metadata = {
  title: 'verification',
  description:
    'How we prove a real person took a real photo — and what that proof does and does not cover.',
};

export default function VerificationPage() {
  return (
    <ContentPage
      title="verification"
      lede="How we prove a real person took a real photo."
      breadcrumbs={[
        { label: 'home', href: ROUTES.home },
        { label: 'about', href: ROUTES.about },
      ]}
    >
      <Prose>
        <p>
          Verification is how we prove a real person took a real photo. When you
          post, you get a link you can share alongside your photo as proof that
          it came from a human with a camera — not from a prompt.
        </p>
        <p>There are two things we check, and they&rsquo;re different:</p>
        <ul>
          <li>
            <strong>
              <Link href={SECTION_LINKS.identity}>Are you a real person?</Link>
            </strong>{' '}
            We confirm you&rsquo;re a unique human, not a bot farm running fifty
            accounts.
          </li>
          <li>
            <strong>
              <Link href={SECTION_LINKS.humanity}>
                Did your camera really take this?
              </Link>
            </strong>{' '}
            We confirm the photo came out of the physical camera on your phone.
          </li>
        </ul>

        <h2>what you actually get</h2>
        <p>
          Once a photo is verified, we generate a unique link for that photo.
          You share it wherever you post — in the caption, in your bio, in the
          comments. Anyone who clicks it sees confirmation that a verified human
          took that photo with a real camera.
        </p>
        <p>
          Your audience doesn&rsquo;t need our app. They don&rsquo;t need an
          account. They just click.
        </p>

        <h2>what we can&rsquo;t promise</h2>
        <Callout>
          <p>
            We verify that a human took a photo with a real camera. We do not
            guarantee that the <em>contents</em> of that photo weren&rsquo;t
            generated by AI — someone can always point a camera at a screen.
          </p>
          <p>
            We&rsquo;re not trying to be perfect. We&rsquo;re trying to force a
            real human into the loop, because we think that alone cuts the sheer
            volume of AI slop people are drowning in. We&rsquo;re pro-human, not
            anti-<PreserveCase>AI</PreserveCase>.
          </p>
        </Callout>

        <h2 id={VERIFICATION_SECTIONS.identity}>
          proving you&rsquo;re a real person
        </h2>
        <p>
          This is a one-time thing. You do it when you register, and then you
          never think about it again.
        </p>
        <p>
          There are two ways through it. Which one you get depends on what our
          identity provider can confirm about you.
        </p>

        <h3>
          option 1: your <PreserveCase>ID</PreserveCase> and a quick video
        </h3>
        <ol>
          <li>You enter some basic personal info.</li>
          <li>You photograph your government-issued ID.</li>
          <li>
            You do a liveness check — a short video where you follow a few
            on-screen prompts, like turning your head or blinking.
          </li>
        </ol>
        <p>
          The video step is what makes the ID meaningful. It confirms a live
          person is actually holding that ID, rather than someone holding up a
          photo of somebody else&rsquo;s license.
        </p>

        <h3>
          option 2: your phone number and <PreserveCase>Social</PreserveCase>
        </h3>
        <ol>
          <li>You enter your phone number and Social Security number.</li>
          <li>
            Our identity provider checks your number against your mobile
            carrier&rsquo;s records — confirming the device is genuinely yours,
            and that the line isn&rsquo;t brand new or recently ported.
          </li>
          <li>
            It cross-checks that against the identity information you submitted.
          </li>
        </ol>
        <p>No ID photo, no video. This one takes seconds.</p>
        <p>
          Either path is answering the same question: is there one real person
          behind this account?
        </p>

        <h2 id={VERIFICATION_SECTIONS.humanity}>
          proving a human took the photo
        </h2>
        <ol>
          <li>You snap a photo in our app.</li>
          <li>
            Your phone&rsquo;s camera quietly signs the photo as it&rsquo;s
            taken — think of it as an invisible watermark baked in at the moment
            of capture.
          </li>
          <li>That signature travels with the photo.</li>
          <li>
            We check the signature, and generate your shareable proof link.
          </li>
        </ol>
        <p>
          This is possible because the camera and the photo get
          cryptographically bound together using content credentials, an open
          standard called C2PA. If you want to go down the rabbit hole:{' '}
          <a
            href={CONTENT_AUTHENTICITY_URL}
            target="_blank"
            rel="noreferrer noopener"
          >
            Content Authenticity Initiative
          </a>
          .
        </p>

        <h2>your privacy</h2>
        <p>
          We ask for identity information so we can confirm you&rsquo;re a
          unique human. That&rsquo;s it.
        </p>
        <p>
          Your ID photo and liveness video go to our identity provider to run
          the check. They&rsquo;re never posted, never attached to your photos,
          and never shown to anyone on the network.
        </p>
        <p>
          We will never share your identity information without your permission.
          It isn&rsquo;t shown on your profile, it isn&rsquo;t attached to your
          photos, and the people clicking your proof link don&rsquo;t see it.
          They only see that a verified human took the photo.
        </p>
        <p>
          One thing worth knowing: if you sell or hand off your account, whoever
          gets it may gain access to your information. So don&rsquo;t.
        </p>

        <h2>frequently asked questions</h2>

        <details>
          <summary>Why is this iOS only?</summary>
          <p>
            Right now the app is iPhone-only. Android support is something we
            want to build.
          </p>
        </details>

        <details>
          <summary>Why only photos?</summary>
          <p>
            Photos are where we&rsquo;re starting. Other content types are
            coming.
          </p>
        </details>

        <details>
          <summary>Why can&rsquo;t I import photos from my camera roll?</summary>
          <p>
            Your iPhone&rsquo;s physical camera does create the signature we
            need — but Apple&rsquo;s built-in Camera app doesn&rsquo;t expose it
            to other apps, so we have no way to read or verify it after the
            fact. That&rsquo;s why the photo has to be taken inside our app.
          </p>
          <p>
            If we build an Android app, we&rsquo;ll be able to support importing
            there.
          </p>
        </details>

        <details>
          <summary>What if I edit my photos?</summary>
          <p>
            Editing happens after capture, which is exactly the point where the
            signature can break. For now, verification works best on photos
            shared as shot. We know this is a real limitation for a lot of
            creators and we&rsquo;re working on it.
          </p>
        </details>

        <details>
          <summary>Can I get banned?</summary>
          <p>
            Yes — if you abuse duplicate accounts, resell accounts, steal
            others&rsquo; content, or obviously photograph AI-generated content,
            we&rsquo;ll remove you from the human network.
          </p>
        </details>
      </Prose>
    </ContentPage>
  );
}
