#!/usr/bin/env node
// The Human Internet: design token generator. Zero dependencies (Node 18+).
//
//   node design-system/build.mjs            # run from the web repo root
//   node design-system/build.mjs --web-only # skip the iOS/Android checkouts
//
// Reads design-system/tokens.json and writes:
//   - web:     the CSS variables file (src/styles/tokens.css), plus a TS copy
//              of the colours for code that can't read CSS (the OG card)
//   - iOS:     DesignTokens.swift
//   - Android: DesignTokens.kt
//   - DESIGN.md (front matter regenerated from tokens) to every repo
// Output locations live in design-system/targets.json. Anything it can't reach
// (e.g. a sibling repo isn't checked out) is skipped with a warning; copies of
// everything always land in design-system/build/ for manual copying.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const DIR = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(DIR, "..");
const tokens = JSON.parse(fs.readFileSync(path.join(DIR, "tokens.json"), "utf8"));
const targets = JSON.parse(fs.readFileSync(path.join(DIR, "targets.json"), "utf8"));
const HEADER = "GENERATED by design-system/build.mjs from tokens.json. DO NOT EDIT. Change tokens.json and re-run.";

// ---------- helpers ----------
const entries = (obj) => Object.entries(obj).filter(([k]) => !k.startsWith("$"));
function resolve(v) {
  if (typeof v !== "string") return v;
  const m = v.match(/^\{(.+)\}$/);
  if (!m) return v;
  const node = m[1].split(".").reduce((o, k) => o?.[k], tokens);
  if (!node) throw new Error(`Unresolved reference ${v}`);
  return resolve(node.$value);
}
const hex = (v) => resolve(v).toUpperCase();
const camel = (s) => s.replace(/-([a-z0-9])/g, (_, c) => c.toUpperCase());
const pascal = (s) => { const c = camel(s); return /^[0-9]/.test(c) ? "X" + c : c[0].toUpperCase() + c.slice(1); };
const swiftId = (s) => { const c = camel(s); return /^[0-9]/.test(c) ? "x" + c : c; };
const r2 = (n) => Math.round(n * 1000) / 1000;

const semantic = entries(tokens.color.semantic).map(([name, t]) => ({
  name, light: hex(t.$value), dark: hex(t.$extensions?.dark ?? t.$value), desc: t.$description ?? "",
}));
const primitives = entries(tokens.color.primitive).map(([name, t]) => ({ name, value: hex(t.$value), desc: t.$description ?? "" }));
const type = entries(tokens.typography).map(([name, t]) => ({
  name, web: t.$value.fontSize, mobile: t.$extensions.mobile.fontSize,
  lh: t.$value.lineHeight, ls: t.$value.letterSpacing, textStyle: t.$extensions.textStyle,
}));
const radius = entries(tokens.radius).map(([n, t]) => ({ name: n, v: t.$value, desc: t.$description ?? "" }));
const spacing = entries(tokens.spacing).map(([n, t]) => ({ name: n, v: t.$value }));
const size = entries(tokens.size).map(([n, t]) => ({ name: n, v: t.$value, desc: t.$description ?? "" }));
const shadow = tokens.shadow.float.$value;
const durations = entries(tokens.motion.duration).map(([n, t]) => ({ name: n, v: t.$value, desc: t.$description ?? "" }));
const easings = entries(tokens.motion.easing).map(([n, t]) => ({ name: n, v: t.$value, desc: t.$description ?? "" }));
const weight = tokens.font.weight.medium.$value;

// ---------- web: tokens.css ----------
function css() {
  const L = [`/* ${HEADER} */`, "", ":root {"];
  L.push("  /* primitives */");
  for (const p of primitives) L.push(`  --ds-${p.name}: ${p.value};`);
  L.push("", "  /* semantic colors (shadcn/ui names) */");
  for (const c of semantic) L.push(`  --${c.name}: ${c.light}; /* ${c.desc} */`);
  L.push("", "  /* type scale (web) */");
  for (const t of type) {
    L.push(`  --ds-text-${t.name}: ${t.web / 16}rem;`);
    L.push(`  --ds-text-${t.name}-lh: ${t.lh};`);
    L.push(`  --ds-text-${t.name}-ls: ${t.ls}em;`);
  }
  L.push(`  --ds-font-weight: ${weight};`);
  L.push("", "  /* radius */");
  for (const r of radius) L.push(`  --ds-radius-${r.name}: ${r.v}px;`);
  L.push("", "  /* spacing */");
  for (const s of spacing) L.push(`  --ds-space-${s.name}: ${s.v}px;`);
  L.push("", "  /* size */");
  for (const s of size) L.push(`  --ds-size-${s.name}: ${s.v}px;`);
  L.push("", "  /* elevation */");
  L.push(`  --ds-shadow-float: ${shadow.offsetX}px ${shadow.offsetY}px ${shadow.blur}px ${shadow.spread}px rgb(0 0 0 / ${shadow.opacity});`);
  L.push("", "  /* motion */");
  for (const d of durations) L.push(`  --ds-duration-${d.name}: ${d.v}ms;`);
  for (const e of easings) L.push(`  --ds-ease-${e.name}: cubic-bezier(${e.v.join(", ")});`);
  L.push("}", "", "/* Dark: PROVISIONAL until the brand defines a dark version */", ".dark {");
  for (const c of semantic) L.push(`  --${c.name}: ${c.dark};`);
  L.push("}", "", "@media (prefers-reduced-motion: reduce) {", "  :root {");
  for (const d of durations) L.push(`    --ds-duration-${d.name}: 0ms;`);
  L.push("  }", "}", "");
  return L.join("\n");
}

// ---------- web: tokens.ts ----------
// Satori, which renders the Open Graph card, resolves no CSS custom
// properties, so that file reads literal values from here instead.
function ts() {
  const L = [`// ${HEADER}`, "", "/** Semantic colours, light. Only for code that can't use the CSS variables. */", "export const colors = {"];
  for (const c of semantic) L.push(`  ${camel(c.name)}: ${JSON.stringify(c.light)}, // ${c.desc}`);
  L.push("} as const;", "");
  return L.join("\n");
}

// ---------- iOS: DesignTokens.swift ----------
function swift() {
  const rgb = (h) => `0x${h.slice(1)}`;
  const L = [`// ${HEADER}`, "//", "// Use these through Theme / Typography / Components; views should not", "// reach for raw numbers or hex values.", "", "import SwiftUI", "import UIKit", "", "public enum DesignTokens {", ""];
  L.push("    // MARK: Colors (light/dark adaptive; dark is PROVISIONAL)");
  L.push("    public enum Colors {");
  for (const c of semantic) L.push(`        /// ${c.desc}`, `        public static let ${swiftId(c.name)} = Color(light: ${rgb(c.light)}, dark: ${rgb(c.dark)})`);
  L.push("    }", "");
  L.push("    // MARK: Typography (one weight: Medium)");
  L.push("    public struct TextStyleToken {");
  L.push("        public let size: CGFloat          // pt at default Dynamic Type size");
  L.push("        public let lineHeight: CGFloat    // multiplier");
  L.push("        public let tracking: CGFloat      // pt (already converted from em)");
  L.push("        public let textStyle: Font.TextStyle // Dynamic Type style to scale with");
  L.push("        public var lineSpacing: CGFloat { max(0, size * lineHeight - size) }");
  L.push("    }");
  L.push(`    public static let fontWeight: Font.Weight = .medium // ${weight}`);
  L.push(`    public static let brandFontName = "${tokens.font.family.brand.$value}"`);
  L.push(`    public static let fallbackFontName = "${tokens.font.family.fallback.$value}"`);
  L.push("    public enum TextStyles {");
  for (const t of type) L.push(`        public static let ${swiftId(t.name)} = TextStyleToken(size: ${t.mobile}, lineHeight: ${t.lh}, tracking: ${r2(t.ls * t.mobile)}, textStyle: .${t.textStyle})`);
  L.push("    }", "");
  L.push("    // MARK: Shape");
  L.push("    public enum Radius {");
  for (const r of radius) L.push(`        public static let ${swiftId(r.name)}: CGFloat = ${r.v} // ${r.desc}`);
  L.push("    }", "");
  L.push("    // MARK: Spacing (4pt grid)");
  L.push("    public enum Space {");
  for (const s of spacing) L.push(`        public static let ${swiftId("s" + s.name)}: CGFloat = ${s.v}`);
  L.push("    }", "");
  L.push("    public enum Size {");
  for (const s of size) L.push(`        public static let ${swiftId(s.name)}: CGFloat = ${s.v} // ${s.desc}`);
  L.push("    }", "");
  L.push("    // MARK: Elevation: only floating layers (sheets, popovers). Cards are flat.");
  L.push("    public enum Shadow {");
  L.push(`        public static let floatColor = Color.black.opacity(${shadow.opacity})`);
  L.push(`        public static let floatRadius: CGFloat = ${shadow.blur / 2}`);
  L.push(`        public static let floatY: CGFloat = ${shadow.offsetY}`);
  L.push("    }", "");
  L.push("    // MARK: Motion. Opacity-only reveals; respect Reduce Motion.");
  L.push("    public enum Motion {");
  for (const d of durations) L.push(`        public static let ${swiftId(d.name)}: Double = ${d.v / 1000} // ${d.desc}`);
  for (const e of easings) L.push(`        /// ${e.desc}`, `        public static func ${swiftId("ease-" + e.name)}(_ duration: Double = base) -> Animation { .timingCurve(${e.v.join(", ")}, duration: duration) }`);
  L.push("    }", "}", "");
  L.push("private extension Color {");
  L.push("    init(light: UInt32, dark: UInt32) {");
  L.push("        func ui(_ v: UInt32) -> UIColor {");
  L.push("            UIColor(red: CGFloat((v >> 16) & 0xFF) / 255, green: CGFloat((v >> 8) & 0xFF) / 255, blue: CGFloat(v & 0xFF) / 255, alpha: 1)");
  L.push("        }");
  L.push("        self.init(uiColor: UIColor { $0.userInterfaceStyle == .dark ? ui(dark) : ui(light) })");
  L.push("    }", "}", "");
  return L.join("\n");
}

// ---------- Android: DesignTokens.kt ----------
function kotlin(pkg) {
  const argb = (h) => `Color(0xFF${h.slice(1)})`;
  const f = (n) => (Number.isInteger(n) ? `${n}f` : `${n}f`);
  const L = [`// ${HEADER}`, `package ${pkg}`, "", "import androidx.compose.animation.core.CubicBezierEasing", "import androidx.compose.ui.graphics.Color", "import androidx.compose.ui.unit.dp", "import androidx.compose.ui.unit.em", "import androidx.compose.ui.unit.sp", "", "object DesignTokens {", ""];
  for (const mode of ["light", "dark"]) {
    L.push(`    /** Semantic colors, ${mode}${mode === "dark" ? " (PROVISIONAL)" : ""}. Use via HumanTheme, not directly. */`);
    L.push(`    object ${mode === "light" ? "Light" : "Dark"} {`);
    for (const c of semantic) L.push(`        val ${pascal(c.name)} = ${argb(c[mode])}`);
    L.push("    }", "");
  }
  L.push("    /** Type scale (sp). One weight: Medium. lineHeight is a multiplier. */");
  L.push("    data class TypeToken(val size: Float, val lineHeight: Float, val letterSpacingEm: Float) {");
  L.push("        val sizeSp get() = size.sp");
  L.push("        val lineHeightSp get() = (size * lineHeight).sp");
  L.push("        val letterSpacing get() = letterSpacingEm.em");
  L.push("    }");
  L.push("    object Type {");
  for (const t of type) L.push(`        val ${pascal(t.name)} = TypeToken(size = ${f(t.mobile)}, lineHeight = ${f(t.lh)}, letterSpacingEm = ${f(t.ls)})`);
  L.push("    }", "");
  L.push("    object Radius {");
  for (const r of radius) L.push(`        val ${pascal(r.name)} = ${r.v}.dp // ${r.desc}`);
  L.push("    }", "");
  L.push("    object Space {");
  for (const s of spacing) L.push(`        val S${s.name} = ${s.v}.dp`);
  L.push("    }", "");
  L.push("    object Size {");
  for (const s of size) L.push(`        val ${pascal(s.name)} = ${s.name === "min-touch" ? 48 : s.v}.dp // ${s.desc}`);
  L.push("    }", "");
  L.push("    /** Only floating layers (sheets, dialogs). Cards are flat. */");
  L.push("    object Shadow {");
  L.push(`        val FloatElevation = ${Math.round(shadow.offsetY / 2)}.dp`);
  L.push(`        val FloatColor = Color(0x${Math.round(shadow.opacity * 255).toString(16).toUpperCase().padStart(2, "0")}000000)`);
  L.push("    }", "");
  L.push("    /** Opacity-only reveals. Respect the system animator-duration setting. */");
  L.push("    object Motion {");
  for (const d of durations) L.push(`        const val ${pascal(d.name)}Ms = ${d.v} // ${d.desc}`);
  for (const e of easings) L.push(`        val Ease${pascal(e.name)} = CubicBezierEasing(${e.v.map(f).join(", ")}) // ${e.desc}`);
  L.push("    }", "}", "");
  return L.join("\n");
}

// ---------- DESIGN.md front matter ----------
function frontMatter() {
  const q = (s) => `"${s}"`;
  const L = ["---", "version: alpha", "name: The Human Internet",
    "description: Design system for The Human Internet, a photo-authenticity app. White canvas, black type, one weight, and an organic hand-made mark that proves a human was here.",
    `# ${HEADER}`, "colors:"];
  for (const c of semantic.filter((c) => c.name !== "ring")) L.push(`  ${c.name}: ${q(c.light)}`);
  L.push("typography:");
  for (const t of type) {
    L.push(`  ${t.name}:`, `    fontFamily: ${tokens.font.family.brand.$value}`, `    fontSize: ${t.web / 16}rem`, `    fontWeight: ${weight}`, `    lineHeight: ${t.lh}`);
    if (t.ls !== 0) L.push(`    letterSpacing: ${t.ls}em`);
  }
  L.push("rounded:");
  for (const r of radius) L.push(`  ${r.name}: ${r.v}px`);
  L.push("spacing:");
  for (const s of spacing) L.push(`  ${s.name}: ${s.v}px`);
  L.push(`components:
  button-primary:
    backgroundColor: "{colors.primary}"
    textColor: "{colors.primary-foreground}"
    typography: "{typography.label}"
    rounded: "{rounded.full}"
    height: ${tokens.size["control-height"].$value}px
    padding: 0 20px
  button-secondary:
    backgroundColor: "{colors.surface}"
    textColor: "{colors.foreground}"
    typography: "{typography.label}"
    rounded: "{rounded.full}"
    height: ${tokens.size["control-height"].$value}px
    padding: 0 20px
  button-secondary-hover:
    backgroundColor: "{colors.surface-hover}"
  button-tertiary:
    textColor: "{colors.foreground}"
    typography: "{typography.label}"
    height: ${tokens.size["control-height"].$value}px
  icon-button:
    backgroundColor: "{colors.surface}"
    textColor: "{colors.foreground}"
    rounded: "{rounded.full}"
    size: ${tokens.size["icon-button"].$value}px
  card:
    backgroundColor: "{colors.surface}"
    textColor: "{colors.foreground}"
    rounded: "{rounded.lg}"
    padding: 16px
  info-card:
    backgroundColor: "{colors.surface}"
    textColor: "{colors.foreground}"
    typography: "{typography.title}"
    rounded: "{rounded.md}"
    padding: 16px 20px
  badge-highlight:
    backgroundColor: "{colors.highlight}"
    textColor: "{colors.highlight-foreground}"
    typography: "{typography.caption}"
    rounded: "{rounded.full}"
  input:
    backgroundColor: "{colors.surface}"
    textColor: "{colors.foreground}"
    typography: "{typography.body}"
    rounded: "{rounded.md}"
    height: ${tokens.size["control-height"].$value}px
    padding: 0 16px
  input-error:
    backgroundColor: "{colors.surface}"
    textColor: "{colors.destructive}"
    typography: "{typography.label}"
    rounded: "{rounded.md}"
  meta-label:
    textColor: "{colors.muted-foreground}"
    typography: "{typography.label}"
  large-subtle-text:
    textColor: "{colors.subtle-foreground}"
    typography: "{typography.title}"
  divider:
    backgroundColor: "{colors.border}"
    height: 1px
  destructive-button:
    backgroundColor: "{colors.destructive}"
    textColor: "{colors.destructive-foreground}"
    typography: "{typography.label}"
    rounded: "{rounded.full}"
---`);
  return L.join("\n");
}

// ---------- write ----------
function write(file, content, label) {
  try {
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, content);
    console.log(`  ✓ ${label}: ${path.relative(ROOT, file) || file}`);
  } catch (e) {
    console.warn(`  ! skipped ${label}: ${e.message}`);
  }
}
const repoExists = (p) => fs.existsSync(p);

const designPath = path.join(DIR, "DESIGN.md");
const body = fs.readFileSync(designPath, "utf8").replace(/^---[\s\S]*?\n---\n?/, "");
const designMd = frontMatter() + "\n" + body.replace(/^\n*/, "\n");
const out = {
  css: css(),
  ts: ts(),
  swift: swift(),
  kt: kotlin(targets.android.package),
};

console.log("Design tokens →");
write(designPath, designMd, "DESIGN.md (master)");
const B = path.join(DIR, "build");
write(path.join(B, "web/tokens.css"), out.css, "build copy");
write(path.join(B, "ios/DesignTokens.swift"), out.swift, "build copy");
write(path.join(B, "android/DesignTokens.kt"), out.kt, "build copy");

write(path.join(ROOT, targets.web.tokensCss), out.css, "web tokens.css");
write(path.join(ROOT, targets.web.tokensTs), out.ts, "web tokens.ts");
write(path.join(ROOT, "DESIGN.md"), designMd, "web DESIGN.md");

if (process.argv.includes("--web-only")) {
  console.log("  - iOS and Android skipped (--web-only); copies are in design-system/build/");
  process.exit(0);
}

for (const [key, file, content] of [["ios", "tokensSwift", out.swift], ["android", "tokensKt", out.kt]]) {
  const repo = path.resolve(ROOT, targets[key].repo);
  if (!repoExists(repo)) { console.warn(`  ! ${key} repo not found at ${repo}; copy from design-system/build/${key}/ manually`); continue; }
  write(path.join(repo, targets[key][file]), content, `${key} tokens`);
  write(path.join(repo, "DESIGN.md"), designMd, `${key} DESIGN.md`);
}
